hotel_api/apps/perfil/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

	url(r'^listar_tipo$', listar_tipo , name='tipo'),
    url(r'^crear_tipo/$', crear_tipo, name='add_tipo'),
    url(r'^eliminar_tipo/$', eliminar_tipo),
    url(r'^buscar_tipo/$', buscar_tipo),
    url(r'^actualizar_tipo/$', actualizar_tipo),

    url(r'^detalle_perfil$', perfil_detail, name= 'detail_perfil'),
    url(r'^edit_perfil$', perfil_edit, name= 'edit_perfil'),

    url(r'^users$', UserList.as_view(), name='user_list'),
    url(r'^user_add$', UserCreate.as_view(), name='user_add'),
    url(r'^user_del/(?P<pk>\d+)$', UserDelete.as_view(), name='user_del'),
    url(r'^user_edit$', user_edit, name= 'user_edit'),

    url(r'^registrar$', RegistrarUsuario.as_view(), name='registrar_usuario'),

    # url(r'^upload', upload, name = 'upload')
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT, }),
]

hotel_api/hotel_main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.contrib.auth.views import logout_then_login, login
from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index.as_view(), name='index'),
    url(r'^home/$', Homepage.as_view(), name='homepage'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^hotel/', include('apps.hotel.urls', namespace='hotel_app')),
    url(r'^perfil/', include('apps.perfil.urls', namespace='perfil_app')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT, }),
]

hotel_api/templates/admin.html
 <div class="panel panel-info">
     <div class="panel-heading">Admin</div>
        <div class="panel-body">
            <ul>
                <li><a href="#" id="tipuser">Tipo de usuarios</a></li>
                <li><a href="#" id="saludo2">Saludo2</a></li>
                <li><a href="#">Link</a></li>
            </ul>
    </div>
</div>

hotel_api/templates/control.html
<script>
$(document).ready(function(){
    $("#contenido").load("{% url 'homepage' %}");
    $("#tipuser").click(function(){
        $("#contenido").load("{% url 'perfil_app:tipo' %}");
         console.log( "You clicked list tipo users" );
    });
});
</script>

hotel_api/templates/homepage.html
<div class="panel panel-info">
    <div class="panel-heading" align="center">
        <h4><strong> Homepage</strong></div>
    </div>
    <div class="panel-body">
        {% if user.is_authenticated %}
        <h2>Bienvenido {{user}}</h2>
        {% else %}
        <h2>
            <a href="{% url "login" %}">Login please</a>
        </h2>
        {% endif %}

        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi recusandae dicta aspernatur ad amet, nesciunt nostrum iure excepturi vero, minima dolorem temporibus cum, laudantium corrupti tempora repudiandae id vitae consequatur.
    </div>
</div>

hotel_api/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>
	{% block title %}{% endblock %}
	</title>
  <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">

  <script src="{% static "js/jquery-1.11.3.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
</head>
<body>
{% include 'navbar.html'%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
            <div id="contenido"></div>
        </div>
        <div class="col-md-2">
            {% include 'admin.html' %}
        </div>
    </div>
</div>

<script>
$(document).ready(function(){
    $("#contenido").load("{% url 'homepage' %}");
    function listar(){
        $("#contenido").load("{% url 'perfil_app:tipo' %}");
    }
    $("#tipuser").click(function(){
        listar();
        console.log( "Hiciste click en listar tipo de usuarios" );
    });
});
</script>
</body>
</html>

hotel_api/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>login</title>
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <style>
    body {
      background-color: #eeeeff;
     background: url("../static/img/interior.jpg") no-repeat fixed center; 
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }
    .borde { 
      border-color: rgba(90,90,255,0.5)  transparent;
      border-style: solid;
      border-width: 15px;
    }
    .borde2 { 
      border-color: rgba(0,0,100,0.7)  transparent;
      border-style: solid;
      border-width: 7px;
    }
    #username {
      background-color: transparent;
      color: orange;
      font-family: "Times New Roman";
      font-size: 20px;
    }
    #password {
      background-color: transparent;
      color: orange;
      font-family: "Times New Roman";
      font-size: 20px;
    }
  </style>
</head>
<body>
  <div class="container" align="center"><br><br><br><br><br>
    <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 borde2">
    <div class=" borde">
      <h1>Login</h1>
      <form class="form-horizontal" method="post" >
      {% csrf_token %}
        <div class="form-group">
          <label class="control-label col-sm-3">Username:</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter user">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3">Password:</label>
          <div class="col-sm-9"> 
            <input type="password" class="form-control" name="password" id="password" placeholder="Enter password">
          </div>
        </div>      
        <div class="form-group"> 
          <div >
            <button type="submit" class="btn btn-success btn-block">Enter</button>
          </div>
        </div>
      </form>
      </div>
      </div>
    </div>
  </div>
</body>
</html>

hotel_api/templates/navbar.html
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Logotipo</a>
  </div>
 
  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Sucursales</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Administrar<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Acción #1</a></li>
          <li><a href="#">Acción #2</a></li>
          <li><a href="#">Acción #3</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #4</a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #5</a></li>
        </ul>
      </li>
    </ul>
 
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Buscar">
      </div>
      <button type="submit" class="btn btn-default">Enviar</button>
    </form>
 
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Enlace #3</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Wellcome 
          {{ user.username|capfirst }} <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Acción #1</a></li>
          <li><a href="#">Acción #2</a></li>
          <li><a href="#">Acción #3</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>